# Start with Python 3.11
FROM python:3.11

# Replace <your_openai_api_key> with your own key
ENV OPENAI_API_KEY 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

# Install Open Interpreter
RUN pip install open-interpreter
